#!/bin/bash
#SBATCH --job-name=Example
#SBATCH -e Example.err.%j
#SBATCH -o Example.out.%j
#SBATCH -t 1-10:10:00
#SBATCH -n 16
####SBATCH -w compute-0-1
####SBATCH -w compute-0-2
#############################
export Project=Example
#############################
module load ansys/v212
export WORKDIR=${SLURM_SUBMIT_DIR}

cd $WORKDIR
$AWP_ROOT212/ansys/bin/ansys212  -np 16 -mpi=intelmpi -b -dir $WORKDIR -i S_F.in -o  Example.txt

exit

